### ISSUE TITLE
Remove Generics Completely from Abstract-LevelDown typings?

### ISSUE THREAD

**Issue by MeirionHughes** [Level/typings#1]
I've already removed the Option Generics - for the sake of reducing coupling to abstract-down's typings. But the Key and Value generics are currently still there. We could remove those as well and perhaps should do so for things like encoding-down, because the return key and value you get from `get` and `iterator` are dependent on the `keyEncoder` and `valueEncoder` override options. 

It would be easy to explicitly type this "override" behavior in `level` and `mem`, but its extremely difficult in `level-up`. 

Currently the generics on Abstract-Down and Encoding-down default to `any`, so they are technically optional at the moment. Thus if a user decides to explicitly set them, with the understanding that the DB can only store those types then they would have the option to do so. 

Thoughts? @vweevers @zixia

**Comment by vweevers** [comment]
I'll copy what I said [here](https://github.com/Level/abstract-leveldown/pull/195#issuecomment-364105124):

> Considering the dynamic nature of everything put together (`abstract-leveldown`, `*asBuffer` options, stores, serialization, `encoding-down`, sublevels, per-operation encodings, etc), using `any` instead of generics does sound like a good idea to me.

In addition, it's pretty clear by now that the generics cost a lot of time and effort. If the choice is between "fully typed but insane" and "loosely typed but clean", it's an easy choice IMHO.

**Comment by vweevers** [comment]
Further discussion can take place in DT.
